### ISSUE TITLE
Copying example on Reference Array page

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/conesite#8]
```
imm hello = "Hello"
fn main():
  mut dessert = jello(hello)

fn jello(mut saying [5; u8]):
  saying = "jello"
  saying
```

This example compiles. When I add  a print <- dessert to main() it still compiles, but gives a segmentation fault at execution.

However, everything works correct when changing the signature of jello to:

fn jello(mut saying [5; u8]) [5; u8]:

adding its return type. This seems to be needed?  Can do a PR if you say so.
[5; u8]

**Comment by jondgoodwin** [comment]
Yes, please do submit a PR on the refarray.html example to correctly add the return type.

However, please also submit an issue on the compiler for seg fault on the original example, as it should generate an error message instead. It should be illegal to assign nil to dessert, and print <- nil should be a function not found error.
